### ISSUE TITLE
How did you pick the images from Microsoft COCO and OpenImages?

### ISSUE THREAD

**Issue by yan99033** [FilippoAleotti/mobilePydnet#13]
I have a follow-up question about issue #11:
In your paper "Real-time single image depth perception in the wild with handheld devices", you mentioned about picking 447k images from the two datasets. Did you systematically select a fixed amount of images across different categories? What's the strategy?

Are you planning to release the WILD dataset as well as the training code?

Great work, by the way.

**Comment by FilippoAleotti** [comment]
Hi,
For the training, I did not apply any content-based strategy, but you can exploit object annotations provided by the datasets to make a content-specific dataset. On the contrary, with the aim of being robust in the wild, I just applied checks in terms of shapes (no portrait images) and I also discarded those images with a black border (if the sum of all the pixels belonging to the first or last 50 columns picture is very low then I skip the image). This means that some images are really hard to explain for a monocular network, but that’s fine because I don’t know which images the network will see at testing time (think about [this](https://filippoaleotti.github.io/demo_live/))
I do not plan to release the dataset, but just the training code and the list of images in the future.

**Comment by yan99033** [comment]
Thanks for the reply. Looking forward to the release of the training code and the list of images.

May I know which links you used to download the datasets?
For Microsoft COCO, is it "2017 Unlabelled images"?
![image](https://user-images.githubusercontent.com/26388965/85047364-ed98c900-b14e-11ea-8ee0-215447e54166.png)

The OpenImages dataset is huge (18TB in total), which one did you use?

**Comment by FilippoAleotti** [comment]
Hi ,sorry for the delay in responding you. I've added the image list in `single_inference` folder.
