### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by cswwp** [FilippoAleotti/mobilePydnet#6]
![image](https://user-images.githubusercontent.com/11901683/75644617-d4423e80-5c7d-11ea-8acd-306864e65a46.png)
Figure1

Hi @FilippoAleotti, really thanks for sharing. I have some questions about training
1 As your readme shows that you train on martport with supervision, as far as i know, the martport3D dataset has up, left, right view image as figure1 shows, all of these in your train set?

2 Do you mind share your training code with supervision?

**Comment by FilippoAleotti** [comment]
Hi,
1) Matterport dataset is RGB-D, so it contains also depth information. I haven’t downloaded it recently, but I think it should still be available in the official website. Let me know if you have problems with it
2) This repository was designed to contain just the mobile applications. You can find the code for train the network in the [original repository](https://github.com/mattpoggi/pydnet) (using BerHu loss instead of the self-supervised one). Again, let me know in case of problems
